### PR TITLE
updated menu bar sun icon

### PR DESCRIPTION
**Pull request by LinusGeffarth**

### CODE REVIEW

**Comment by HarshilShah** [comment]
Thank you for opening a pull request!

I’m curious what your issue with the original icon/goal with this one is. The glyph is mostly the same, but the size doesn’t really harmonise with the system icons.

**Comment by LinusGeffarth** [comment]
Hey, I didn't like the margins at the top and bottom. That's why :)
Plus I do think it fits well with the moon icon. I installed it in my version on my machine and like it :)

**Comment by HarshilShah** [comment]
I think I’m gonna have to reject this PR; to me the icon just doesn’t seem consistent with the system icons, sorry

**Comment by LinusGeffarth** [comment]
That's okay :)

**Pull request closed without merging**
